[package]
name = "rustymiddle-http"
description = "Hyper HTTP/1.1 and HTTP/2 adapters for rustymiddle"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
bytes.workspace = true
http.workspace = true
http-body.workspace = true
http-body-util.workspace = true
hyper.workspace = true
hyper-boring.workspace = true
hyper-util.workspace = true
rustymiddle-core = { version = "=0.1.0", path = "../proxy-core" }
rustymiddle-tls = { version = "=0.1.0", path = "../proxy-tls" }
thiserror.workspace = true
tokio.workspace = true
tower-service.workspace = true
tracing.workspace = true

[lints]
workspace = true
