//! Compiles the desktop `WebUI` templates into an embedded protocol.

use std::{
    env,
    fmt::Write as _,
    fs,
    path::{Path, PathBuf},
};

use webui::{BuildOptions, CssStrategy, Plugin, ProjectionManifestSource, build};

fn main() {
    let manifest_dir = PathBuf::from(
        env::var_os("CARGO_MANIFEST_DIR").expect("Cargo provides CARGO_MANIFEST_DIR"),
    );
    let ui_dir = manifest_dir.join("../../apps/desktop/ui");
    println!("cargo:rerun-if-changed={}", ui_dir.join("src").display());
    println!(
        "cargo:rerun-if-changed={}",
        ui_dir.join("dist/app.js").display()
    );
    for asset in ["app.css", "monaco-editor.worker.js", "monaco-ts.worker.js"] {
        println!(
            "cargo:rerun-if-changed={}",
            ui_dir.join("dist").join(asset).display()
        );
    }
    println!(
        "cargo:rerun-if-changed={}",
        ui_dir.join("dist/webui-projection.json").display()
    );
    compile_webui(&ui_dir);
}

fn compile_webui(ui_dir: &Path) {
    let output_dir = PathBuf::from(env::var_os("OUT_DIR").expect("Cargo provides OUT_DIR"));
    let projection_manifest = ui_dir.join("dist/webui-projection.json");
    let client_bundle = ui_dir.join("dist/app.js");
    assert!(
        client_bundle.is_file() && projection_manifest.is_file(),
        "missing generated UI assets; run scripts/build-desktop.ps1"
    );

    let result = build(BuildOptions {
        app_dir: ui_dir.join("src"),
        entry: "index.html".to_owned(),
        css: CssStrategy::Link,
        plugin: Some(Plugin::WebUI),
        css_file_name_template: "[name]-[hash].[ext]".to_owned(),
        css_public_base: Some("/".to_owned()),
        projection_manifests: vec![ProjectionManifestSource::Path(projection_manifest)],
        ..BuildOptions::default()
    })
    .unwrap_or_else(|error| panic!("failed to compile WebUI templates: {error:?}"));

    let protocol_path = output_dir.join("protocol.bin");
    fs::write(&protocol_path, result.protocol_bytes).expect("write WebUI protocol");
    let mut generated = String::from(
        "// Generated by build.rs. Do not edit.\n\
         /// Compiled `WebUI` protocol bytes.\n\
         pub const PROTOCOL_BYTES: &[u8] = include_bytes!(",
    );
    push_path_literal(&mut generated, &protocol_path);
    generated.push_str(
        ");\n\n/// Compiled CSS assets keyed by application-origin path.\n\
         pub const CSS_ASSETS: &[(&str, &[u8])] = &[\n",
    );
    for (filename, contents) in result.css_files {
        assert!(
            filename
                .bytes()
                .all(|byte| byte.is_ascii_alphanumeric() || matches!(byte, b'-' | b'_' | b'.')),
            "WebUI emitted an unsafe CSS filename: {filename}"
        );
        let path = output_dir.join(&filename);
        fs::write(&path, contents).expect("write WebUI CSS asset");
        generated.push_str("    (\"/");
        generated.push_str(&filename);
        generated.push_str("\", include_bytes!(");
        push_path_literal(&mut generated, &path);
        generated.push_str(")),\n");
    }
    generated.push_str("];\n");
    fs::write(output_dir.join("assets.rs"), generated).expect("write WebUI asset index");
}

fn push_path_literal(target: &mut String, path: &Path) {
    write!(target, "{:?}", path.to_string_lossy()).expect("writing to a String cannot fail");
}
