//! Compiles the desktop `WebUI` templates into an embedded protocol.

use std::{
    env,
    fmt::Write as _,
    fs,
    path::{Path, PathBuf},
};

use webui::{BuildOptions, CssStrategy, Plugin, ProjectionManifestSource, build};

fn main() {
    let manifest_dir = PathBuf::from(
        env::var_os("CARGO_MANIFEST_DIR").expect("Cargo provides CARGO_MANIFEST_DIR"),
    );
    let ui_dir = manifest_dir.join("../../apps/desktop/ui");
    println!("cargo:rerun-if-changed={}", ui_dir.join("src").display());
    println!("cargo:rerun-if-changed={}", ui_dir.join("dist").display());
    println!(
        "cargo:rerun-if-changed={}",
        ui_dir.join("../icons/icon.svg").display()
    );
    println!(
        "cargo:rerun-if-changed={}",
        ui_dir.join("dist/webui-projection.json").display()
    );
    compile_webui(&ui_dir);
}

fn compile_webui(ui_dir: &Path) {
    let output_dir = PathBuf::from(env::var_os("OUT_DIR").expect("Cargo provides OUT_DIR"));
    let projection_manifest = ui_dir.join("dist/webui-projection.json");
    let client_bundle = ui_dir.join("dist/app.js");
    assert!(
        client_bundle.is_file() && projection_manifest.is_file(),
        "missing generated UI assets; run scripts/build-desktop.ps1"
    );

    let result = build(BuildOptions {
        app_dir: ui_dir.join("src"),
        entry: "index.html".to_owned(),
        css: CssStrategy::Link,
        plugin: Some(Plugin::WebUI),
        css_file_name_template: "[name]-[hash].[ext]".to_owned(),
        css_public_base: Some("/".to_owned()),
        projection_manifests: vec![ProjectionManifestSource::Path(projection_manifest)],
        ..BuildOptions::default()
    })
    .unwrap_or_else(|error| panic!("failed to compile WebUI templates: {error:?}"));

    let protocol_path = output_dir.join("protocol.bin");
    fs::write(&protocol_path, result.protocol_bytes).expect("write WebUI protocol");
    let mut generated = String::from(
        "// Generated by build.rs. Do not edit.\n\
         /// Compiled `WebUI` protocol bytes.\n\
         pub const PROTOCOL_BYTES: &[u8] = include_bytes!(",
    );
    push_path_literal(&mut generated, &protocol_path);
    generated.push_str(
        ");\n\n/// Compiled CSS assets keyed by application-origin path.\n\
         pub const CSS_ASSETS: &[(&str, &[u8])] = &[\n",
    );
    for (filename, contents) in result.css_files {
        assert!(
            filename
                .bytes()
                .all(|byte| byte.is_ascii_alphanumeric() || matches!(byte, b'-' | b'_' | b'.')),
            "WebUI emitted an unsafe CSS filename: {filename}"
        );
        let path = output_dir.join(&filename);
        fs::write(&path, contents).expect("write WebUI CSS asset");
        generated.push_str("    (\"/");
        generated.push_str(&filename);
        generated.push_str("\", include_bytes!(");
        push_path_literal(&mut generated, &path);
        generated.push_str(")),\n");
    }
    generated.push_str("];\n");
    embed_client_assets(ui_dir, &mut generated);
    fs::write(output_dir.join("assets.rs"), generated).expect("write WebUI asset index");
}

fn embed_client_assets(ui_dir: &Path, generated: &mut String) {
    let manifest: serde_json::Value = serde_json::from_slice(
        &fs::read(ui_dir.join("dist/client-assets.json")).expect("read client asset manifest"),
    )
    .expect("parse client asset manifest");
    generated.push_str("\n/// Current bundler outputs allowlisted by application-origin path.\npub const CLIENT_ASSETS: &[(&str, &str, &[u8])] = &[\n");
    for asset in manifest
        .as_array()
        .expect("client asset manifest is an array")
    {
        let filename = asset["file"].as_str().expect("client asset filename");
        let public_path = asset["path"].as_str().expect("client asset public path");
        let content_type = asset["contentType"]
            .as_str()
            .expect("client asset MIME type");
        let parts: Vec<_> = filename.split('/').collect();
        assert!(parts.len() == 1 || parts.len() == 2 && parts[0] == "chunks");
        assert!(parts.iter().all(|part| {
            !part.is_empty()
                && !matches!(*part, "." | "..")
                && part
                    .bytes()
                    .all(|byte| byte.is_ascii_alphanumeric() || matches!(byte, b'-' | b'_' | b'.'))
        }));
        assert_eq!(public_path, format!("/{filename}"));
        assert!(matches!(
            content_type,
            "text/javascript; charset=utf-8" | "text/css; charset=utf-8"
        ));
        let path = ui_dir.join("dist").join(filename);
        write!(
            generated,
            "    ({public_path:?}, {content_type:?}, include_bytes!("
        )
        .expect("write asset entry");
        push_path_literal(generated, &path);
        generated.push_str(")),\n");
    }
    generated.push_str("];\n");
}

fn push_path_literal(target: &mut String, path: &Path) {
    write!(target, "{:?}", path.to_string_lossy()).expect("writing to a String cannot fail");
}
