//! Compiles the desktop `WebUI` templates into an embedded protocol.

use std::{
    collections::BTreeSet,
    env,
    fmt::Write as _,
    fs,
    path::{Path, PathBuf},
};

use webui::{BuildOptions, CssStrategy, Plugin, ProjectionManifestSource, build};

struct AssetSource {
    public_path: String,
    content_type: &'static str,
    source_path: PathBuf,
    expected_bytes: Option<u64>,
}

fn main() {
    let manifest_dir = PathBuf::from(
        env::var_os("CARGO_MANIFEST_DIR").expect("Cargo provides CARGO_MANIFEST_DIR"),
    );
    let ui_dir = manifest_dir.join("../../apps/desktop/ui");
    println!("cargo:rerun-if-changed={}", ui_dir.join("src").display());
    println!("cargo:rerun-if-changed={}", ui_dir.join("dist").display());
    println!(
        "cargo:rerun-if-changed={}",
        ui_dir.join("../icons").display()
    );
    println!(
        "cargo:rerun-if-changed={}",
        ui_dir.join("dist/webui-projection.json").display()
    );
    compile_webui(&ui_dir);
}

fn compile_webui(ui_dir: &Path) {
    let output_dir = PathBuf::from(env::var_os("OUT_DIR").expect("Cargo provides OUT_DIR"));
    let projection_manifest = ui_dir.join("dist/webui-projection.json");
    let client_bundle = ui_dir.join("dist/app.js");
    assert!(
        client_bundle.is_file() && projection_manifest.is_file(),
        "missing generated UI assets; run scripts/build-desktop.ps1"
    );

    let result = build(BuildOptions {
        app_dir: ui_dir.join("src"),
        entry: "index.html".to_owned(),
        css: CssStrategy::Link,
        plugin: Some(Plugin::WebUI),
        css_file_name_template: "[name]-[hash].[ext]".to_owned(),
        css_public_base: Some("/".to_owned()),
        projection_manifests: vec![ProjectionManifestSource::Path(projection_manifest)],
        ..BuildOptions::default()
    })
    .unwrap_or_else(|error| panic!("failed to compile WebUI templates: {error:?}"));

    let protocol_path = output_dir.join("protocol.bin");
    fs::write(&protocol_path, result.protocol_bytes).expect("write WebUI protocol");
    let mut generated = String::from(
        "// Generated by build.rs. Do not edit.\n\
         const PROTOCOL_BYTES: &[u8] = include_bytes!(",
    );
    push_path_literal(&mut generated, &protocol_path);
    generated.push_str(");\n");
    let mut sources = vec![
        AssetSource {
            public_path: "/document.css".to_owned(),
            content_type: "text/css; charset=utf-8",
            source_path: ui_dir.join("dist/document.css"),
            expected_bytes: None,
        },
        AssetSource {
            public_path: "/favicon.ico".to_owned(),
            content_type: "image/x-icon",
            source_path: ui_dir.join("../icons/icon.ico"),
            expected_bytes: None,
        },
        AssetSource {
            public_path: "/transmog-icon.svg".to_owned(),
            content_type: "image/svg+xml; charset=utf-8",
            source_path: ui_dir.join("../icons/icon.svg"),
            expected_bytes: None,
        },
    ];
    for (filename, contents) in result.css_files {
        assert!(
            filename
                .bytes()
                .all(|byte| byte.is_ascii_alphanumeric() || matches!(byte, b'-' | b'_' | b'.')),
            "WebUI emitted an unsafe CSS filename: {filename}"
        );
        let path = output_dir.join(&filename);
        fs::write(&path, contents).expect("write WebUI CSS asset");
        sources.push(AssetSource {
            public_path: format!("/{filename}"),
            content_type: "text/css; charset=utf-8",
            source_path: path,
            expected_bytes: None,
        });
    }
    sources.extend(client_assets(ui_dir));
    embed_assets(&output_dir, &sources, &mut generated);
    fs::write(output_dir.join("assets.rs"), generated).expect("write WebUI asset index");
}

fn client_assets(ui_dir: &Path) -> Vec<AssetSource> {
    let manifest: serde_json::Value = serde_json::from_slice(
        &fs::read(ui_dir.join("dist/client-assets.json")).expect("read client asset manifest"),
    )
    .expect("parse client asset manifest");
    let mut sources = Vec::new();
    for asset in manifest
        .as_array()
        .expect("client asset manifest is an array")
    {
        let filename = asset["file"].as_str().expect("client asset filename");
        let public_path = asset["path"].as_str().expect("client asset public path");
        let content_type = asset["contentType"]
            .as_str()
            .expect("client asset MIME type");
        let parts: Vec<_> = filename.split('/').collect();
        assert!(parts.len() == 1 || parts.len() == 2 && parts[0] == "chunks");
        assert!(parts.iter().all(|part| {
            !part.is_empty()
                && !matches!(*part, "." | "..")
                && part
                    .bytes()
                    .all(|byte| byte.is_ascii_alphanumeric() || matches!(byte, b'-' | b'_' | b'.'))
        }));
        assert_eq!(public_path, format!("/{filename}"));
        assert!(matches!(
            content_type,
            "text/javascript; charset=utf-8"
                | "text/css; charset=utf-8"
                | "application/json; charset=utf-8"
        ));
        sources.push(AssetSource {
            public_path: public_path.to_owned(),
            content_type: if content_type.starts_with("text/css;") {
                "text/css; charset=utf-8"
            } else if content_type.starts_with("application/json;") {
                "application/json; charset=utf-8"
            } else {
                "text/javascript; charset=utf-8"
            },
            source_path: ui_dir.join("dist").join(filename),
            expected_bytes: Some(asset["bytes"].as_u64().expect("client asset byte length")),
        });
    }
    sources
}

fn embed_assets(output_dir: &Path, sources: &[AssetSource], generated: &mut String) {
    writeln!(
        generated,
        "\nstatic EMBEDDED_ASSETS: [EmbeddedAsset; {}] = [",
        sources.len()
    )
    .expect("write asset inventory");
    let params = brotli::enc::BrotliEncoderParams {
        quality: 9,
        lgwin: 22,
        ..Default::default()
    };
    let mut paths = BTreeSet::new();
    for asset in sources {
        assert!(paths.insert(&asset.public_path), "duplicate UI asset path");
        let contents = fs::read(&asset.source_path).expect("read UI asset");
        assert!(
            contents.len() <= 16 * 1024 * 1024,
            "UI asset exceeds its byte limit"
        );
        if let Some(expected) = asset.expected_bytes {
            assert_eq!(
                contents.len() as u64,
                expected,
                "client asset manifest is stale"
            );
        }
        let mut compressed = Vec::new();
        brotli::BrotliCompress(&mut contents.as_slice(), &mut compressed, &params)
            .expect("compress UI asset");
        let mut decoded = Vec::new();
        brotli::BrotliDecompress(&mut compressed.as_slice(), &mut decoded)
            .expect("verify compressed UI asset");
        assert_eq!(contents, decoded, "UI asset compression changed its bytes");
        let path = output_dir
            .join("compressed")
            .join(format!("{}.br", asset.public_path.trim_start_matches('/')));
        fs::create_dir_all(path.parent().expect("compressed asset parent"))
            .expect("create compressed asset directory");
        fs::write(&path, compressed).expect("write compressed UI asset");
        write!(
            generated,
            "    EmbeddedAsset::new({:?}, {:?}, include_bytes!(",
            asset.public_path, asset.content_type
        )
        .expect("write asset entry");
        push_path_literal(generated, &path);
        let length = contents.len().to_string();
        let length = length
            .as_bytes()
            .rchunks(3)
            .rev()
            .map(|chunk| std::str::from_utf8(chunk).expect("byte length digits"))
            .collect::<Vec<_>>()
            .join("_");
        writeln!(generated, "), {length}),").expect("write asset length");
    }
    generated.push_str("];\n\n#[cfg(test)]\nconst ORIGINAL_ASSETS: &[(&str, &[u8])] = &[\n");
    // Original bytes exist only in test binaries, so release round-trip checks
    // can compare actual protocol responses without retaining a second copy.
    for asset in sources {
        write!(generated, "    ({:?}, include_bytes!(", asset.public_path)
            .expect("write original asset entry");
        push_path_literal(generated, &asset.source_path);
        generated.push_str(")),\n");
    }
    generated.push_str("];\n");
}

fn push_path_literal(target: &mut String, path: &Path) {
    write!(target, "{:?}", path.to_string_lossy()).expect("writing to a String cannot fail");
}
