[package]
name = "transmog-runtime"
description = "Listener, routing, pooling, and orchestration for Transmog"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
boring.workspace = true
bytes.workspace = true
http.workspace = true
http-body.workspace = true
http-body-util.workspace = true
hyper.workspace = true
hyper-util.workspace = true
transmog-core = { version = "=0.1.0", path = "../proxy-core" }
transmog-client-identity = { version = "=0.1.0", path = "../client-identity" }
transmog-content = { version = "=0.1.0", path = "../proxy-content" }
transmog-h3 = { version = "=0.1.0", path = "../proxy-h3" }
transmog-http = { version = "=0.1.0", path = "../proxy-http" }
transmog-network = { version = "=0.1.0", path = "../network" }
transmog-tls = { version = "=0.1.0", path = "../proxy-tls" }
transmog-websocket = { version = "=0.1.0", path = "../proxy-websocket" }
thiserror.workspace = true
tokio.workspace = true
tokio-boring.workspace = true
tracing.workspace = true

[lints]
workspace = true

[dev-dependencies]
quiche.workspace = true
