[package]
name = "rustymiddle-runtime"
description = "Listener, routing, pooling, and orchestration for rustymiddle"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
boring.workspace = true
bytes.workspace = true
http.workspace = true
http-body.workspace = true
http-body-util.workspace = true
hyper.workspace = true
hyper-util.workspace = true
rustymiddle-core = { version = "=0.1.0", path = "../proxy-core" }
rustymiddle-content = { version = "=0.1.0", path = "../proxy-content" }
rustymiddle-h3 = { version = "=0.1.0", path = "../proxy-h3" }
rustymiddle-http = { version = "=0.1.0", path = "../proxy-http" }
rustymiddle-tls = { version = "=0.1.0", path = "../proxy-tls" }
rustymiddle-websocket = { version = "=0.1.0", path = "../proxy-websocket" }
thiserror.workspace = true
tokio.workspace = true
tokio-boring.workspace = true
tracing.workspace = true

[lints]
workspace = true

[dev-dependencies]
quiche.workspace = true
