//! Compiles `WebUI` templates and delegates Windows resources to Tauri.

use std::{
    env,
    fmt::Write as _,
    fs,
    path::{Path, PathBuf},
};

use webui::{BuildOptions, CssStrategy, Plugin, ProjectionManifestSource, build};

fn main() {
    println!("cargo:rerun-if-changed=ui/src");
    println!("cargo:rerun-if-changed=ui/dist/app.js");
    println!("cargo:rerun-if-changed=ui/dist/webui-projection.json");
    println!("cargo:rerun-if-changed=tauri.conf.json");
    println!("cargo:rerun-if-changed=capabilities");

    compile_webui();

    #[cfg(windows)]
    tauri_build::build();
}

fn compile_webui() {
    let manifest_dir = PathBuf::from(
        env::var_os("CARGO_MANIFEST_DIR").expect("Cargo provides CARGO_MANIFEST_DIR"),
    );
    let output_dir =
        PathBuf::from(env::var_os("OUT_DIR").expect("Cargo provides OUT_DIR")).join("webui");
    let projection_manifest = manifest_dir.join("ui/dist/webui-projection.json");
    let client_bundle = manifest_dir.join("ui/dist/app.js");

    assert!(
        client_bundle.is_file(),
        "missing ui/dist/app.js; run `npm ci` and `npm run build` in apps/desktop/ui"
    );
    assert!(
        projection_manifest.is_file(),
        "missing ui/dist/webui-projection.json; run `npm ci` and `npm run build` in apps/desktop/ui"
    );

    let result = build(BuildOptions {
        app_dir: manifest_dir.join("ui/src"),
        entry: "index.html".to_owned(),
        css: CssStrategy::Link,
        plugin: Some(Plugin::WebUI),
        css_file_name_template: "[name]-[hash].[ext]".to_owned(),
        css_public_base: Some("/".to_owned()),
        projection_manifests: vec![ProjectionManifestSource::Path(projection_manifest)],
        ..BuildOptions::default()
    })
    .unwrap_or_else(|error| panic!("failed to compile WebUI templates: {error}"));

    fs::create_dir_all(&output_dir).expect("create WebUI output directory");
    let protocol_path = output_dir.join("protocol.bin");
    fs::write(&protocol_path, result.protocol_bytes).expect("write WebUI protocol");

    let mut generated = String::from(
        "// Generated by build.rs. Do not edit.\n\
         /// Compiled `WebUI` protocol bytes embedded in the application.\n\
         pub const PROTOCOL_BYTES: &[u8] = include_bytes!(",
    );
    push_path_literal(&mut generated, &protocol_path);
    generated.push_str(
        ");\n\n/// Compiled `WebUI` CSS assets keyed by application-origin path.\n\
         pub const CSS_ASSETS: &[(&str, &[u8])] = &[\n",
    );

    for (filename, contents) in result.css_files {
        assert!(
            filename
                .bytes()
                .all(|byte| byte.is_ascii_alphanumeric() || matches!(byte, b'-' | b'_' | b'.')),
            "WebUI emitted an unsafe CSS filename: {filename}"
        );
        let path = output_dir.join(&filename);
        fs::write(&path, contents).expect("write WebUI CSS asset");
        generated.push_str("    (\"");
        generated.push('/');
        generated.push_str(&filename);
        generated.push_str("\", include_bytes!(");
        push_path_literal(&mut generated, &path);
        generated.push_str(")),\n");
    }
    generated.push_str("];\n");

    fs::write(output_dir.join("assets.rs"), generated).expect("write WebUI asset index");
}

fn push_path_literal(target: &mut String, path: &Path) {
    write!(target, "{:?}", path.to_string_lossy()).expect("writing to a String cannot fail");
}
