[package]
name = "transmog"
description = "Runnable Transmog explicit proxy and CA operator tool"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[[bin]]
name = "transmog-cli"
path = "src/main.rs"

[dependencies]
rpassword.workspace = true
zeroize.workspace = true
transmog-key-protection = { version = "=0.1.2", path = "../key-protection" }
sysinfo.workspace = true
transmog-network = { version = "=0.1.2", path = "../network" }
bytes.workspace = true
boring.workspace = true
serde.workspace = true
serde_json.workspace = true
tempfile.workspace = true
transmog-host-windows = { version = "=0.1.2", path = "../host-windows" }
transmog-session = { version = "=0.1.2", path = "../proxy-session" }
transmog-capture = { version = "=0.1.2", path = "../proxy-capture" }
transmog-content = { version = "=0.1.2", path = "../proxy-content" }
transmog-core = { version = "=0.1.2", path = "../proxy-core" }
transmog-runtime = { version = "=0.1.2", path = "../proxy-runtime" }
transmog-saz = { version = "=0.1.2", path = "../proxy-saz" }
transmog-tls = { version = "=0.1.2", path = "../proxy-tls" }
tokio.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true

[target.'cfg(unix)'.dependencies]
rustix = { version = "=1.1.5", features = ["fs"] }

[target.'cfg(windows)'.build-dependencies]
tauri-winres = "=0.3.6"

[lints]
workspace = true
