[package]
name = "transmog"
description = "Runnable Transmog explicit proxy and CA operator tool"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[[bin]]
name = "transmog-cli"
path = "src/main.rs"

[dependencies]
bytes.workspace = true
transmog-capture = { version = "=0.1.0", path = "../proxy-capture" }
transmog-content = { version = "=0.1.0", path = "../proxy-content" }
transmog-core = { version = "=0.1.0", path = "../proxy-core" }
transmog-runtime = { version = "=0.1.0", path = "../proxy-runtime" }
transmog-saz = { version = "=0.1.0", path = "../proxy-saz" }
transmog-tls = { version = "=0.1.0", path = "../proxy-tls" }
tokio.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true

[lints]
workspace = true
