[package]
name = "rustymiddle"
description = "Runnable rustymiddle explicit proxy and CA operator tool"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
bytes.workspace = true
rustymiddle-capture = { version = "=0.1.0", path = "../proxy-capture" }
rustymiddle-core = { version = "=0.1.0", path = "../proxy-core" }
rustymiddle-runtime = { version = "=0.1.0", path = "../proxy-runtime" }
rustymiddle-saz = { version = "=0.1.0", path = "../proxy-saz" }
rustymiddle-tls = { version = "=0.1.0", path = "../proxy-tls" }
tokio.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true

[lints]
workspace = true
