#![no_main]

use std::{num::NonZeroUsize, sync::OnceLock};

use bytes::Bytes;
use libfuzzer_sys::fuzz_target;
use rustymiddle_content::{
    ContentCodecError, ContentCoding, ContentCodingStack, ContentDecoder, ContentEncoder,
    ContentLimits,
};
use rustymiddle_core::{BodyFrame, HeaderBlock, HeaderField};
use tokio::runtime::{Builder, Runtime};

const CODINGS: [ContentCoding; 4] = [
    ContentCoding::Gzip,
    ContentCoding::Brotli,
    ContentCoding::Deflate,
    ContentCoding::Zstd,
];
const MAX_BODY: usize = 64 * 1024 + 1;
const MAX_CODEC_BYTES: usize = 1024 * 1024;

fuzz_target!(|data: &[u8]| {
    if data.len() < 8 || data.len() > 16 * 1024 {
        return;
    }
    runtime().block_on(round_trip(data));
});

async fn round_trip(data: &[u8]) {
    let layer_count = usize::from(selector(data[0]) % 5);
    let selected = (0..layer_count)
        .map(|index| CODINGS[usize::from(selector(data[index + 1])) % CODINGS.len()])
        .collect::<Vec<_>>();
    let header = selected
        .iter()
        .map(|coding| coding.as_str())
        .collect::<Vec<_>>()
        .join(", ");
    let headers = if header.is_empty() {
        HeaderBlock::new()
    } else {
        HeaderBlock::from_fields(vec![
            HeaderField::try_new("content-encoding", header).expect("canonical header is valid"),
        ])
    };
    let stack = ContentCodingStack::from_headers(
        &headers,
        NonZeroUsize::new(CODINGS.len()).expect("coding depth"),
    )
    .expect("generated coding stack is valid");
    assert_eq!(stack.encode_order().collect::<Vec<_>>(), selected);

    let source = make_source(selector(data[5]), &data[8..]);
    let encode_chunk = usize::from(selector(data[6]) % 128) + 1;
    let decode_chunk = usize::from(selector(data[7]) % 128) + 1;
    let limits = limits();

    let mut encoded = source.clone();
    for coding in stack.encode_order() {
        encoded = encode_layer(coding, &encoded, encode_chunk, limits).await;
    }
    assert!(encoded.len() <= MAX_CODEC_BYTES);

    let mut decoded = encoded;
    for coding in stack.decode_order() {
        decoded = decode_layer(coding, &decoded, decode_chunk, limits);
    }
    assert_eq!(decoded, source);
}

async fn encode_layer(
    coding: ContentCoding,
    input: &[u8],
    chunk_size: usize,
    limits: ContentLimits,
) -> Vec<u8> {
    let mut encoder = ContentEncoder::new(coding, limits).expect("valid encoder configuration");
    let mut output = Vec::new();
    for chunk in input.chunks(chunk_size) {
        append_data(
            &mut output,
            encoder
                .on_frame(BodyFrame::Data(Bytes::copy_from_slice(chunk)))
                .await
                .expect("bounded generated input must encode"),
        );
    }
    append_data(
        &mut output,
        encoder
            .finish()
            .await
            .expect("generated stream must finish"),
    );
    assert!(matches!(
        encoder.finish().await,
        Err(ContentCodecError::AlreadyFinished { .. })
    ));
    assert!(matches!(
        encoder.on_frame(BodyFrame::Data(Bytes::new())).await,
        Err(ContentCodecError::AlreadyFinished { .. })
    ));
    output
}

fn decode_layer(
    coding: ContentCoding,
    input: &[u8],
    chunk_size: usize,
    limits: ContentLimits,
) -> Vec<u8> {
    let mut decoder = ContentDecoder::new(coding, limits).expect("valid decoder configuration");
    let mut output = Vec::new();
    for chunk in input.chunks(chunk_size) {
        append_data(
            &mut output,
            decoder
                .on_frame(BodyFrame::Data(Bytes::copy_from_slice(chunk)))
                .expect("stream generated by our encoder must decode"),
        );
    }
    append_data(
        &mut output,
        decoder.finish().expect("generated stream must finish"),
    );
    assert!(matches!(
        decoder.finish(),
        Err(ContentCodecError::AlreadyFinished { .. })
    ));
    assert!(matches!(
        decoder.on_frame(BodyFrame::Data(Bytes::new())),
        Err(ContentCodecError::AlreadyFinished { .. })
    ));
    output
}

fn append_data(output: &mut Vec<u8>, frames: Vec<BodyFrame>) {
    for frame in frames {
        match frame {
            BodyFrame::Data(bytes) => {
                output.extend_from_slice(&bytes);
                assert!(output.len() <= MAX_CODEC_BYTES);
            }
            BodyFrame::Trailers(_) => panic!("round-trip helper did not submit trailers"),
        }
    }
}

fn make_source(size_selector: u8, pattern: &[u8]) -> Vec<u8> {
    let size = match size_selector % 16 {
        0 => 0,
        1 => 1,
        2 => 63,
        3 => 64,
        4 => 1_023,
        5 => 1_024,
        6 => 4_095,
        7 => 4_096,
        8 => 64 * 1024 - 1,
        9 => 64 * 1024,
        10 => MAX_BODY,
        _ => pattern.len().min(16 * 1024),
    };
    let mut output = Vec::with_capacity(size);
    if pattern.is_empty() {
        output.resize(size, size_selector);
    } else {
        output.extend(pattern.iter().copied().cycle().take(size));
    }
    output
}

fn limits() -> ContentLimits {
    ContentLimits::new(
        NonZeroUsize::new(MAX_CODEC_BYTES).expect("encoded limit"),
        NonZeroUsize::new(MAX_CODEC_BYTES).expect("decoded limit"),
        NonZeroUsize::new(MAX_CODEC_BYTES).expect("output limit"),
        NonZeroUsize::new(16 * 1024 * 1024).expect("window limit"),
        NonZeroUsize::new(1_024).expect("ratio limit"),
        MAX_CODEC_BYTES,
        NonZeroUsize::new(CODINGS.len()).expect("coding depth"),
    )
}

fn runtime() -> &'static Runtime {
    static RUNTIME: OnceLock<Runtime> = OnceLock::new();
    RUNTIME.get_or_init(|| {
        Builder::new_current_thread()
            .enable_time()
            .build()
            .expect("fuzz runtime must initialize")
    })
}

const fn selector(value: u8) -> u8 {
    match value {
        b'0'..=b'9' => value - b'0',
        b'a'..=b'f' => value - b'a' + 10,
        b'A'..=b'F' => value - b'A' + 10,
        _ => value,
    }
}
